// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAR2JGpEr1tapqXhQsgnvPCOff2ssazo',
    appId: '1:910209650050:web:8cf90639c85ad4bb2f939b',
    messagingSenderId: '910209650050',
    projectId: 'scribby4-5d3db',
    authDomain: 'scribby4-5d3db.firebaseapp.com',
    storageBucket: 'scribby4-5d3db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJI1jvDvKcaGYSU0F1cwQDSQFbeW0Um3w',
    appId: '1:910209650050:android:52f64326cf2cf49b2f939b',
    messagingSenderId: '910209650050',
    projectId: 'scribby4-5d3db',
    storageBucket: 'scribby4-5d3db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJzyI17swOG3dA0CW0ChD3ofBGuBiih68',
    appId: '1:910209650050:ios:b3a4e49a0cdd79b12f939b',
    messagingSenderId: '910209650050',
    projectId: 'scribby4-5d3db',
    storageBucket: 'scribby4-5d3db.firebasestorage.app',
    iosBundleId: 'com.nodamngoodstudios.scribby4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJzyI17swOG3dA0CW0ChD3ofBGuBiih68',
    appId: '1:910209650050:ios:b3a4e49a0cdd79b12f939b',
    messagingSenderId: '910209650050',
    projectId: 'scribby4-5d3db',
    storageBucket: 'scribby4-5d3db.firebasestorage.app',
    iosBundleId: 'com.nodamngoodstudios.scribby4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAR2JGpEr1tapqXhQsgnvPCOff2ssazo',
    appId: '1:910209650050:web:27f309b3fe9711d62f939b',
    messagingSenderId: '910209650050',
    projectId: 'scribby4-5d3db',
    authDomain: 'scribby4-5d3db.firebaseapp.com',
    storageBucket: 'scribby4-5d3db.firebasestorage.app',
  );
}
